// app/layout.tsx

import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "./theme-provider";
import RoleWrapper from "./components/roleWrapper/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wigoh Intake Form ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <RoleWrapper>{children}</RoleWrapper>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
